// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<main.Session>;

export function ListSessions():Promise<Array<main.Session>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResumeSession(arg1:string):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;
